#dist: trusty
sudo: required

services:
    - docker

language: go

go:
    - tip
<<<<<<< HEAD

env:
    - GO111MODULE=on

# https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
install: true

before_script: 
    - docker build -t drand-it . #docker-compose should be self-sufficient, but fails on travis...
=======
>>>>>>> 246580c89478d335ddfbe1c84b8e3afc01153128

script:
    - make test-unit
    # keep environnement variable for sudo
    - sudo -E env "PATH=$PATH" make test-integration

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
        sudo docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        sudo docker push dedis/drand:latest;
    fi

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
<<<<<<< HEAD
=======

before_install:
    - docker pull byrnedo/alpine-curl

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  #- provider: script
    #script: docker push dedis/drand:$TRAVIS_TAG
    #on:
        #tags: true
        #condition: $TRAVIS_OS_NAME = linux
>>>>>>> 246580c89478d335ddfbe1c84b8e3afc01153128
