#dist: trusty
sudo: required

services:
    - docker

language: go

go:
    - "1.10.x"

script:
    - go test ./...
    - sudo ./docker_test.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
        sudo docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        sudo docker push dedis/drand;
    fi
