#dist: trusty
sudo: required

services:
    - docker

language: go

go:
    - tip

#script:
    #- go test ./...
    #- ./docker_test.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dedis/drand;
    fi
